import turtle
turtle.speed(5)
turtle.setheading(0)
# plus
turtle.penup()
turtle.goto(0, 30)
turtle.color("red")
turtle.pendown()
turtle.fillcolor("red")
turtle.begin_fill()
turtle.forward(250)
turtle.right(90)
turtle.forward(60)
turtle.right(90)
turtle.forward(560)
turtle.right(90)
turtle.forward(60)
turtle.right(90)
turtle.forward(250)
turtle.end_fill()
turtle.penup()
# plus_up
turtle.goto(0, -30)
turtle.setheading(90)
turtle.color("red")
turtle.pendown()
turtle.fillcolor("red")
turtle.begin_fill()
turtle.forward(200)
turtle.left(90)
turtle.forward(60)
turtle.left(90)
turtle.forward(340)
turtle.left(90)
turtle.forward(60)
turtle.left(90)
turtle.forward(200)
turtle.end_fill()
turtle.penup()
# triangle_1
turtle.goto(20, 50)
turtle.setheading(90)
turtle.color("blue")
turtle.pendown()
turtle.fillcolor("blue")
turtle.begin_fill()
turtle.forward(120)
turtle.right(90)
turtle.forward(160)
turtle.right(143)
turtle.forward(200)
turtle.end_fill()
turtle.penup()
# triangle_2
turtle.goto(20, -50)
turtle.setheading(-90)
turtle.color("blue")
turtle.pendown()
turtle.fillcolor("blue")
turtle.begin_fill()
turtle.forward(120)
turtle.left(90)
turtle.forward(160)
turtle.left(143)
turtle.forward(200)
turtle.end_fill()
turtle.penup()
# triangle_3
turtle.goto(-80, -50)
turtle.setheading(-90)
turtle.color("blue")
turtle.pendown()
turtle.fillcolor("blue")
turtle.begin_fill()
turtle.forward(120)
turtle.right(90)
turtle.forward(160)
turtle.right(143)
turtle.forward(200)
turtle.end_fill()
turtle.penup()
# triangle_4
turtle.goto(-80, 50)
turtle.setheading(90)
turtle.color("blue")
turtle.pendown()
turtle.fillcolor("blue")
turtle.begin_fill()
turtle.forward(120)
turtle.left(90)
turtle.forward(160)
turtle.left(143)
turtle.forward(200)
turtle.end_fill()
turtle.penup()
# mini_triangle_1
turtle.goto(-310, 140)
turtle.setheading(-90)
turtle.color("blue")
turtle.pendown()
turtle.fillcolor("blue")
turtle.begin_fill()
turtle.forward(90)
turtle.left(90)
turtle.forward(120)
turtle.left(143)
turtle.forward(150)
turtle.end_fill()
turtle.penup()
# mini_triangle_2
turtle.goto(-310, -140)
turtle.setheading(90)
turtle.color("blue")
turtle.pendown()
turtle.fillcolor("blue")
turtle.begin_fill()
turtle.forward(90)
turtle.right(90)
turtle.forward(120)
turtle.right(143)
turtle.forward(150)
turtle.end_fill()
turtle.penup()
# mini_triangle_3
turtle.goto(250, -140)
turtle.setheading(90)
turtle.color("blue")
turtle.pendown()
turtle.fillcolor("blue")
turtle.begin_fill()
turtle.forward(90)
turtle.left(90)
turtle.forward(120)
turtle.left(143)
turtle.forward(150)
turtle.end_fill()
turtle.penup()
# mini_triangle_4
turtle.goto(250, 140)
turtle.setheading(-90)
turtle.color("blue")
turtle.pendown()
turtle.fillcolor("blue")
turtle.begin_fill()
turtle.forward(90)
turtle.right(90)
turtle.forward(120)
turtle.right(143)
turtle.forward(150)
turtle.end_fill()
turtle.penup()
# stick_1
turtle.goto(-310, 150)
turtle.setheading(90)
turtle.color("red")
turtle.pendown()
turtle.fillcolor("red")
turtle.begin_fill()
turtle.forward(15)
turtle.right(127)
turtle.forward(190)
turtle.right(143)
turtle.forward(20)
turtle.right(37)
turtle.forward(165)
turtle.end_fill()
turtle.penup()
# stick_2
turtle.goto(-260, -170)
turtle.setheading(180)
turtle.color("red")
turtle.pendown()
turtle.fillcolor("red")
turtle.begin_fill()
turtle.forward(20)
turtle.right(143)
turtle.forward(200)
turtle.right(37)
turtle.forward(20)
turtle.right(143)
turtle.forward(180)
turtle.end_fill()
turtle.penup()
# stick_3
turtle.goto(250, -170)
turtle.setheading(90)
turtle.color("red")
turtle.pendown()
turtle.fillcolor("red")
turtle.begin_fill()
turtle.forward(15)
turtle.left(53)
turtle.forward(170)
turtle.left(37)
turtle.forward(20)
turtle.left(143)
turtle.forward(170)
turtle.end_fill()
turtle.penup()
# stick_4
turtle.goto(200, 170)
turtle.setheading(0)
turtle.color("red")
turtle.pendown()
turtle.fillcolor("red")
turtle.begin_fill()
turtle.forward(20)
turtle.right(143)
turtle.forward(200)
turtle.right(37)
turtle.forward(20)
turtle.right(143)
turtle.forward(190)
turtle.end_fill()
turtle.penup()
turtle.done()



